import type { DriveItem } from "@/lib/stores/use-drive-browser-store"

export const mockDriveData: DriveItem[] = [
  // Root level folders
  {
    id: "folder-1",
    name: "Documents",
    type: "folder",
    mimeType: "application/vnd.google-apps.folder",
    modifiedAt: "2024-01-15T10:30:00Z",
    backupStatus: "backedUp",
  },
  {
    id: "folder-2",
    name: "Photos",
    type: "folder",
    mimeType: "application/vnd.google-apps.folder",
    modifiedAt: "2024-01-14T15:45:00Z",
    backupStatus: "pending",
  },
  {
    id: "folder-3",
    name: "Work Projects",
    type: "folder",
    mimeType: "application/vnd.google-apps.folder",
    modifiedAt: "2024-01-13T09:20:00Z",
    backupStatus: "backedUp",
  },

  // Root level files
  {
    id: "file-1",
    name: "Resume.pdf",
    type: "file",
    mimeType: "application/pdf",
    size: "2.4 MB",
    modifiedAt: "2024-01-12T14:30:00Z",
    backupStatus: "backedUp",
  },
  {
    id: "file-2",
    name: "Budget 2024.xlsx",
    type: "file",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: "1.2 MB",
    modifiedAt: "2024-01-11T11:15:00Z",
    backupStatus: "failed",
  },
  {
    id: "file-3",
    name: "Meeting Notes.docx",
    type: "file",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: "856 KB",
    modifiedAt: "2024-01-10T16:45:00Z",
    backupStatus: "untracked",
  },

  // Files in Documents folder
  {
    id: "file-4",
    name: "Contract Template.pdf",
    type: "file",
    mimeType: "application/pdf",
    size: "3.1 MB",
    modifiedAt: "2024-01-09T13:20:00Z",
    backupStatus: "backedUp",
    parentId: "folder-1",
  },
  {
    id: "file-5",
    name: "Invoice #001.pdf",
    type: "file",
    mimeType: "application/pdf",
    size: "1.8 MB",
    modifiedAt: "2024-01-08T10:30:00Z",
    backupStatus: "pending",
    parentId: "folder-1",
  },
  {
    id: "subfolder-1",
    name: "Legal",
    type: "folder",
    mimeType: "application/vnd.google-apps.folder",
    modifiedAt: "2024-01-07T12:00:00Z",
    backupStatus: "backedUp",
    parentId: "folder-1",
  },

  // Files in Photos folder
  {
    id: "file-6",
    name: "vacation-2024.jpg",
    type: "file",
    mimeType: "image/jpeg",
    size: "4.2 MB",
    modifiedAt: "2024-01-06T18:30:00Z",
    backupStatus: "backedUp",
    parentId: "folder-2",
  },
  {
    id: "file-7",
    name: "profile-pic.png",
    type: "file",
    mimeType: "image/png",
    size: "2.1 MB",
    modifiedAt: "2024-01-05T14:15:00Z",
    backupStatus: "ignored",
    parentId: "folder-2",
  },
  {
    id: "file-8",
    name: "screenshot-2024-01-04.png",
    type: "file",
    mimeType: "image/png",
    size: "1.5 MB",
    modifiedAt: "2024-01-04T09:45:00Z",
    backupStatus: "untracked",
    parentId: "folder-2",
  },

  // Files in Work Projects folder
  {
    id: "file-9",
    name: "Project Proposal.pptx",
    type: "file",
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: "5.7 MB",
    modifiedAt: "2024-01-03T11:30:00Z",
    backupStatus: "backedUp",
    parentId: "folder-3",
  },
  {
    id: "file-10",
    name: "Client Feedback.docx",
    type: "file",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: "1.3 MB",
    modifiedAt: "2024-01-02T15:20:00Z",
    backupStatus: "pending",
    parentId: "folder-3",
  },

  // Files in Legal subfolder
  {
    id: "file-11",
    name: "NDA Template.pdf",
    type: "file",
    mimeType: "application/pdf",
    size: "2.8 MB",
    modifiedAt: "2024-01-01T10:00:00Z",
    backupStatus: "backedUp",
    parentId: "subfolder-1",
  },
  {
    id: "file-12",
    name: "Terms of Service.docx",
    type: "file",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: "2.2 MB",
    modifiedAt: "2023-12-31T16:30:00Z",
    backupStatus: "failed",
    parentId: "subfolder-1",
  },
]
